language: node_js

node_js:
  - "10"

sudo: false

cache:
  directories:
    - node_modules

script:
  - "npm test"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

notifications:
  email:
    - honza@hommer.cz
